# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bf284c9cb9de73ac1e15f7ae13293c16886eba10815a5b30008ebe9bac33dfeedd9a9c186ae538a6bbde38546bfe7a5e79366999347531ccdb6f140da8f09e6

test:
  secret_key_base: be3d5c6488264306181bf86327bb5d1df94011e2965f8f7a6aef7e2783b925c26015967780abb14e63559126ece31bdf2dafecccf26b812871b5b708da3729f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
